version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Admin@10525597
      MYSQL_DATABASE: linkedin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Mount a volume for MySQL data on the host

  linkedin-tool:
    image: 10525597/linkedin-tool:latest # This is the image of spring-boot app pulling from docker-hub repo
    container_name: linkedin-tool
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/linkedin
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Admin@10525597
      - REMOTE_WEBDRIVER_URL=http://selenium-hub:4444
      - REMOTE_WEBDRIVER_USERNAME=admin
      - REMOTE_WEBDRIVER_PASSWORD=vmo@123
    volumes:
      - backend_data:/app/data  # Mount a volume for application data
  chrome:
    image: selenium/node-chrome:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.18.1-20240224
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    volumes:
      - ./volume/config.toml:/opt/selenium/config.toml
volumes:
  mysql_data:  # Define the volume for MySQL data
  backend_data:  # Define the volume for application data