spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linkedin
    username: root
    password: Admin@10525597
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
  threshold:
    console: TRACE
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} - %clr(%-5level) - %msg%n'
