spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linkedin
    username: root
    password: Admin@10525597
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
remote:
  web-driver:
    url: http://localhost:4444
    username: admin
    password: vmo@123