server:
  port: 8081

spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.web: DEBUG
  threshold:
    console: TRACE

sftp:
  host: ftp.hanstack.vn
  username: hanstack
  port: 21
  password: Admin@10525597
